# Generated by Django 3.1.1 on 2020-09-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_auto_20200921_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.IntegerField()),
                ('Employee_Name', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
