# Generated by Django 3.1.1 on 2020-09-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0003_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
